# Generated by Django 2.1 on 2018-11-12 20:49

import cloudinary.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Имя продукта')),
                ('subtitle', models.CharField(help_text='Пример - "Напій ультрапастеризований гречаний 2,5% жиру"', max_length=255, verbose_name='Текст под названием продукта')),
                ('title_subtitle_color', models.CharField(max_length=7, verbose_name='Код цвета заголовка и подзаголовка (web HEX)')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Картинка')),
                ('cereal_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Картинка зерна')),
                ('inner_gradient_color', models.CharField(max_length=7, verbose_name='Код внутреннего цвета градиента (web HEX)')),
                ('outer_gradient_color', models.CharField(max_length=7, verbose_name='Код внешнего цвета градиента (web HEX)')),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='Каждый новый абзац с новой строки. Без пустых строк!', size=None, verbose_name='Первый абзац текста')),
                ('list_heading', models.CharField(max_length=255, verbose_name='Заголовок перед списком')),
                ('about_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Элемент списка'), help_text='Каждый новый абзац с новой строки. Без пустых строк!', size=None, verbose_name='Список особенностецй продукта')),
                ('silly_comment', models.CharField(max_length=255, verbose_name='Смешной заголовок под списком')),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Калории в ккал')),
                ('proteins', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Белки, г')),
                ('carbohydrates', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Углеводы, г')),
                ('cholesterol', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Холестерин')),
            ],
            options={
                'verbose_name': 'Продукт-укр',
                'verbose_name_plural': 'Продукты-укр',
                'db_table': 'products_ukr',
            },
        ),
        migrations.CreateModel(
            name='ProductRus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Имя продукта')),
                ('subtitle', models.CharField(help_text='Пример - "Напій ультрапастеризований гречаний 2,5% жиру"', max_length=255, verbose_name='Текст под названием продукта')),
                ('title_subtitle_color', models.CharField(max_length=7, verbose_name='Код цвета заголовка и подзаголовка (web HEX)')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Картинка')),
                ('cereal_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Картинка зерна')),
                ('inner_gradient_color', models.CharField(max_length=7, verbose_name='Код внутреннего цвета градиента (web HEX)')),
                ('outer_gradient_color', models.CharField(max_length=7, verbose_name='Код внешнего цвета градиента (web HEX)')),
                ('content', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='Каждый новый абзац с новой строки. Без пустых строк!', size=None, verbose_name='Первый абзац текста')),
                ('list_heading', models.CharField(max_length=255, verbose_name='Заголовок перед списком')),
                ('about_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Элемент списка'), help_text='Каждый новый абзац с новой строки. Без пустых строк!', size=None, verbose_name='Список особенностецй продукта')),
                ('silly_comment', models.CharField(max_length=255, verbose_name='Смешной заголовок под списком')),
                ('calories', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Калории в ккал')),
                ('proteins', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Белки, г')),
                ('carbohydrates', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Углеводы, г')),
                ('cholesterol', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Холестерин')),
            ],
            options={
                'verbose_name': 'Продукт-рус',
                'verbose_name_plural': 'Продукты-рус',
                'db_table': 'products_rus',
            },
        ),
    ]
