# Generated by Django 2.1 on 2018-12-03 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inner_gradient_color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='outer_gradient_color',
        ),
    ]
