# Generated by Django 2.1 on 2018-12-11 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0002_auto_20181203_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title_subtitle_color',
        ),
    ]
