# Generated by Django 2.1 on 2018-12-14 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0003_remove_product_title_subtitle_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='big_cardboard_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес маленькой упаковки'),
        ),
        migrations.AddField(
            model_name='product',
            name='small_cardboard_weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес маленькой упаковки'),
        ),
    ]
