# Generated by Django 2.1 on 2018-12-18 14:40

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0004_auto_20181214_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_small',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='Изображение статьи'),
            preserve_default=False,
        ),
    ]
