# Generated by Django 2.1 on 2018-12-18 14:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0005_product_image_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_small',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Изображение статьи'),
        ),
    ]
