# Generated by Django 2.1 on 2018-12-18 16:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_api', '0007_auto_20181218_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='content',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='Каждый новый абзац с новой строки. Без пустых строк!         Для выделения текста жирным шрифтом - поставьте две звёздочки          ** до и после выделения.', size=None, verbose_name='Основной текст'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content_rus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), help_text='Каждый новый абзац с новой строки. Без пустых строк!         Для выделения текста жирным шрифтом - поставьте две звёздочки          ** до и после выделения.', size=None, verbose_name='Основной текст НА РУССКОМ'),
        ),
    ]
