# Generated by Django 2.1 on 2018-12-11 11:39

import cloudinary.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название рецепта')),
                ('title_rus', models.CharField(max_length=300, verbose_name='Название рецепта НА РУССКОМ')),
                ('subtitle', models.TextField(default='', verbose_name='Подзаголовок')),
                ('subtitle_rus', models.TextField(default='', verbose_name='Подзаголовок на РУССКОМ')),
                ('ingridients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Элемент списка'), help_text='Каждый новый элемент с новой строки. Без пустых строк!', size=None, verbose_name='Список ингридиентов')),
                ('ingridients_rus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Элемент списка'), help_text='Каждый новый элемент с новой строки. Без пустых строк!', size=None, verbose_name='Список ингридиентов на РУССКОМ')),
                ('howto', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Элемент списка'), help_text='Каждый новый элемент с новой строки. Без пустых строк!', size=None, verbose_name='Метод преготовления')),
                ('howto_rus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Элемент списка'), help_text='Каждый новый элемент с новой строки. Без пустых строк!', size=None, verbose_name='Метод преготовления')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Веганское')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Вегетарианское')),
                ('endline', models.TextField(max_length=300, verbose_name='Заключительное слово на РУССКОМ')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Изображение статьи')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'db_table': 'recipes',
            },
        ),
    ]
