# Generated by Django 2.1 on 2018-12-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0003_auto_20181211_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='subtitle',
            field=models.CharField(default='', max_length=300, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subtitle_rus',
            field=models.CharField(default='', max_length=300, verbose_name='Подзаголовок на РУССКОМ'),
        ),
    ]
