# Generated by Django 2.1 on 2018-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0004_auto_20181211_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='bold_text',
            field=models.TextField(default='', verbose_name='текс под подзаголовком'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='bold_text_rus',
            field=models.TextField(default='', verbose_name='текс под подзаголовком на РУССКОМ'),
            preserve_default=False,
        ),
    ]
