# Generated by Django 2.1 on 2018-12-11 13:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0005_auto_20181211_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='howto_rus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, verbose_name='Элемент списка'), help_text='Каждый новый элемент с новой строки. Без пустых строк!', size=None, verbose_name='Метод преготовления на РУССКОМ'),
        ),
    ]
