# Generated by Django 2.1 on 2018-12-14 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0006_auto_20181211_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_not_hypolactasian',
            field=models.BooleanField(default=False, verbose_name='Для тех, кно не переносит лактозу'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='is_vegetarian',
            field=models.BooleanField(default=True, verbose_name='Вегетарианское'),
        ),
    ]
