# Generated by Django 2.1 on 2018-12-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0007_auto_20181214_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='is_not_hypolactasian',
            field=models.BooleanField(default=False, verbose_name='Для тех, кто не переносит лактозу'),
        ),
    ]
