# Generated by Django 2.1 on 2018-12-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0008_auto_20181218_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='bold_text',
            field=models.TextField(verbose_name='Tекс под подзаголовком'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='bold_text_rus',
            field=models.TextField(verbose_name='Tекс под подзаголовком на РУССКОМ'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='subtitle_rus',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Подзаголовок на РУССКОМ'),
        ),
    ]
